"""init

Revision ID: 16624f16cc5f
Revises:
Create Date: 2026-10-05 00:08:34.620116

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "16624f16cc5f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
